In [102]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from tensorflow.keras import Model
from tensorflow.keras.layers import Input
from keras.layers import Dense
from keras.optimizers import SGD,Adam
from tensorflow.keras.optimizers import Adam

In [104]:
import pandas as pd

# 파일 읽기 (구분자가 공백이므로 delim_whitespace=True 설정)
df = pd.read_csv("C://Ai-class/seeds_dataset.txt", delim_whitespace=True, header=None)

# 데이터 확인
df

C:\Users\hash0\AppData\Local\Temp\ipykernel_3724\2131574415.py:4: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv("C://Ai-class/seeds_dataset.txt", delim_whitespace=True, header=None)


0      1       2      3      4      5      6  7
0    15.26  14.84  0.8710  5.763  3.312  2.221  5.220  1
1    14.88  14.57  0.8811  5.554  3.333  1.018  4.956  1
2    14.29  14.09  0.9050  5.291  3.337  2.699  4.825  1
3    13.84  13.94  0.8955  5.324  3.379  2.259  4.805  1
4    16.14  14.99  0.9034  5.658  3.562  1.355  5.175  1
..     ...    ...     ...    ...    ...    ...    ... ..
205  12.19  13.20  0.8783  5.137  2.981  3.631  4.870  3
206  11.23  12.88  0.8511  5.140  2.795  4.325  5.003  3
207  13.20  13.66  0.8883  5.236  3.232  8.315  5.056  3
208  11.84  13.21  0.8521  5.175  2.836  3.598  5.044  3
209  12.30  13.34  0.8684  5.243  2.974  5.637  5.063  3

[210 rows x 8 columns]

In [106]:
df.columns = [
    "Area", "Perimeter", "Compactness", "Kernel Length",
    "Kernel Width", "Asymmetry Coefficient", "Kernel Groove Length", "Class"
]
df

Area  Perimeter  Compactness  Kernel Length  Kernel Width  \
0    15.26      14.84       0.8710          5.763         3.312   
1    14.88      14.57       0.8811          5.554         3.333   
2    14.29      14.09       0.9050          5.291         3.337   
3    13.84      13.94       0.8955          5.324         3.379   
4    16.14      14.99       0.9034          5.658         3.562   
..     ...        ...          ...            ...           ...   
205  12.19      13.20       0.8783          5.137         2.981   
206  11.23      12.88       0.8511          5.140         2.795   
207  13.20      13.66       0.8883          5.236         3.232   
208  11.84      13.21       0.8521          5.175         2.836   
209  12.30      13.34       0.8684          5.243         2.974   

     Asymmetry Coefficient  Kernel Groove Length  Class  
0                    2.221                 5.220      1  
1                    1.018                 4.956      1  
2                    2.699                 4.825      1  
3                    2.259                 4.805      1  
4                    1.355                 5.175      1  
..                     ...                   ...    ...  
205                  3.631                 4.870      3  
206                  4.325                 5.003      3  
207                  8.315                 5.056      3  
208                  3.598                 5.044      3  
209                  5.637                 5.063      3  

[210 rows x 8 columns]

In [108]:
X = df.drop(columns=["Class"])
y = df["Class"] 

In [110]:
X = X.values
Y = pd.get_dummies(y).values

In [112]:
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0) 
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((168, 7), (42, 7), (168, 3), (42, 3))

# 케라스를 사용하는 방법 3가지 
### 1. Sequential 모델을 만들고 모델에 필요한 레이어를 추가하는 방법

In [115]:
model = Sequential()

model.add(Dense(10,input_shape=(X_train.shape[1],),activation='relu'))
model.add(Dense(20,activation='relu'))
model.add(Dense(15,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(3,activation='softmax'))

model.compile(optimizer = 'adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.summary()

C:\Users\hash0\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_45 (Dense)                     │ (None, 10)                  │              80 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_46 (Dense)                     │ (None, 20)                  │             220 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_47 (Dense)                     │ (None, 15)                  │             315 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_48 (Dense)                     │ (None, 10)                  │             160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_49 (Dense)                     │ (None, 3)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 808 (3.16 KB)

 Trainable params: 808 (3.16 KB)

 Non-trainable params: 0 (0.00 B)

In [117]:
model_history=model.fit(x=X_train, y=y_train, epochs=20, batch_size=8,validation_data= (X_test,y_test))
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - accuracy: 0.2710 - loss: 1.2782 - val_accuracy: 0.2143 - val_loss: 1.1225
Epoch 2/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.2973 - loss: 1.1040 - val_accuracy: 0.4762 - val_loss: 1.0580
Epoch 3/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4193 - loss: 1.0584 - val_accuracy: 0.5238 - val_loss: 1.0182
Epoch 4/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4816 - loss: 1.0253 - val_accuracy: 0.5238 - val_loss: 0.9794
Epoch 5/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4985 - loss: 0.9866 - val_accuracy: 0.6190 - val_loss: 0.9373
Epoch 6/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5841 - loss: 0.9380 - val_accuracy: 0.6190 - val_loss: 0.8908
Epoch 7/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5940 - loss: 0.9003 - val_accuracy: 0.6429 - val_loss: 0.8311
Epoch 8/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5798 - loss: 0.8456 - val_accuracy: 0.6429 - v

In [119]:
#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.90      0.69      0.78        13
           1       0.87      0.81      0.84        16
           2       0.76      1.00      0.87        13

    accuracy                           0.83        42
   macro avg       0.84      0.83      0.83        42
weighted avg       0.85      0.83      0.83        42

[[ 9  2  2]
 [ 1 13  2]
 [ 0  0 13]]


### 2. 함수형 API를 사용하는 방법

In [122]:
# 입력 정의
inputs = Input(shape=(X_train.shape[1],))

# 레이어 연결
x = Dense(10, activation='relu')(inputs)
x = Dense(20, activation='relu')(x)
x = Dense(15, activation='relu')(x)
x = Dense(10, activation='relu')(x)
outputs = Dense(3, activation='softmax')(x)

# 모델 생성
model = Model(inputs=inputs, outputs=outputs)

# 컴파일
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [124]:
# 학습
model.fit(X_train, y_train, epochs=20, batch_size=8, validation_data=(X_test, y_test))
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)
# 평가
loss, acc = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {acc:.4f}")


Epoch 1/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - accuracy: 0.5152 - loss: 1.1043 - val_accuracy: 0.4524 - val_loss: 1.0711
Epoch 2/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.5428 - loss: 1.0596 - val_accuracy: 0.5476 - val_loss: 1.0523
Epoch 3/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5218 - loss: 1.0438 - val_accuracy: 0.5714 - val_loss: 1.0228
Epoch 4/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6895 - loss: 1.0146 - val_accuracy: 0.5238 - val_loss: 1.0015
Epoch 5/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6761 - loss: 0.9811 - val_accuracy: 0.5000 - val_loss: 0.9779
Epoch 6/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7300 - loss: 0.9481 - val_accuracy: 0.5238 - val_loss: 0.9589
Epoch 7/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7318 - loss: 0.9385 - val_accuracy: 0.8095 - val_loss: 0.9206
Epoch 8/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6893 - loss: 0.8829 - val_accuracy: 0.8571 - v

In [126]:
#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.83      0.77      0.80        13
           1       0.82      0.88      0.85        16
           2       1.00      1.00      1.00        13

    accuracy                           0.88        42
   macro avg       0.89      0.88      0.88        42
weighted avg       0.88      0.88      0.88        42

[[10  3  0]
 [ 2 14  0]
 [ 0  0 13]]


### 3. Model의 클래스를 상속받아 나만의 클래스를 정의하는 방법

In [129]:
class SeedClassifier(Model):
    def __init__(self):
        super(SeedClassifier, self).__init__()
        self.d1 = Dense(10, activation='relu')
        self.d2 = Dense(20, activation='relu')
        self.d3 = Dense(15, activation='relu')
        self.d4 = Dense(10, activation='relu')
        self.out = Dense(3, activation='softmax')

    def call(self, inputs):
        x = self.d1(inputs)
        x = self.d2(x)
        x = self.d3(x)
        x = self.d4(x)
        return self.out(x)

# 모델 생성 및 컴파일
model = SeedClassifier()
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [131]:
# 학습
model.fit(X_train, y_train, epochs=20, batch_size=8, validation_data=(X_test, y_test))
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)
# 평가
loss, acc = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {acc:.4f}")

Epoch 1/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.3921 - loss: 1.1235 - val_accuracy: 0.3810 - val_loss: 1.0626
Epoch 2/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.3479 - loss: 1.0762 - val_accuracy: 0.5000 - val_loss: 1.0671
Epoch 3/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.5254 - loss: 1.0592 - val_accuracy: 0.5238 - val_loss: 1.0493
Epoch 4/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4106 - loss: 1.0598 - val_accuracy: 0.5476 - val_loss: 1.0237
Epoch 5/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.4024 - loss: 1.0296 - val_accuracy: 0.5476 - val_loss: 0.9953
Epoch 6/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.4818 - loss: 0.9885 - val_accuracy: 0.5476 - val_loss: 0.9996
Epoch 7/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.5564 - loss: 0.9808 - val_accuracy: 0.5952 - val_loss: 0.9758
Epoch 8/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4855 - loss: 0.9590 - val_accuracy: 0.6190 - v

In [133]:
#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.73      0.62      0.67        13
           1       0.87      0.81      0.84        16
           2       0.81      1.00      0.90        13

    accuracy                           0.81        42
   macro avg       0.80      0.81      0.80        42
weighted avg       0.81      0.81      0.80        42

[[ 8  2  3]
 [ 3 13  0]
 [ 0  0 13]]
