In [1]:
import pandas as pd
import numpy as np

file_path = "C:/Ai-class/car_evaluation.csv"  
df = pd.read_csv(file_path)

# 데이터프레임 확인
print(df.head())

   vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc


In [3]:
# 각 열별 결측치 개수 확인
missing_values = df.isnull().sum()

# 결측치 비율(%) 계산
missing_ratio = (df.isnull().sum() / len(df)) * 100

# 결과 출력
missing_df = pd.DataFrame({"결측치 개수": missing_values, "결측치 비율(%)": missing_ratio})
print(missing_df)

         결측치 개수  결측치 비율(%)
vhigh         0        0.0
vhigh.1       0        0.0
2             0        0.0
2.1           0        0.0
small         0        0.0
low           0        0.0
unacc         0        0.0


In [5]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

print(df["unacc"].value_counts())  # 클래스 개수 출력
print(df["unacc"].value_counts(normalize=True) * 100)  # 비율(%) 출력

unacc
unacc    1209
acc       384
good       69
vgood      65
Name: count, dtype: int64
unacc
unacc    70.005790
acc      22.235090
good      3.995368
vgood     3.763752
Name: proportion, dtype: float64


In [17]:
from sklearn.preprocessing import LabelEncoder

# 모든 범주형 컬럼을 Label Encoding
label_encoders = {}
for col in df.columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le  # 나중에 역변환할 때 사용 가능

# 변환된 데이터 확인
print(df.head())

   vhigh  vhigh.1  2  2.1  small  low  unacc
0      3        3  0    0      2    2      2
1      3        3  0    0      2    0      2
2      3        3  0    0      1    1      2
3      3        3  0    0      1    2      2
4      3        3  0    0      1    0      2


In [19]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [21]:
print(df.head())

   vhigh  vhigh.1  2  2.1  small  low  unacc
0      3        3  0    0      2    2      2
1      3        3  0    0      2    0      2
2      3        3  0    0      1    1      2
3      3        3  0    0      1    2      2
4      3        3  0    0      1    0      2


In [23]:
# 입력(X)와 타깃(y) 분리
X = df.drop(columns=["unacc"])  # 'Survived' 컬럼 제외 (입력 데이터)
y = df["unacc"]  # 'Survived' 컬럼만 저장 (타깃 데이터)

# 확인
print(X.head())  # 입력 데이터
print(y.head())  # 레이블 (타깃 변수)

   vhigh  vhigh.1  2  2.1  small  low
0      3        3  0    0      2    2
1      3        3  0    0      2    0
2      3        3  0    0      1    1
3      3        3  0    0      1    2
4      3        3  0    0      1    0
0    2
1    2
2    2
3    2
4    2
Name: unacc, dtype: int32


In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

In [27]:
# DT 모델 생성 및 학습
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

# 예측 수행
pred_dt = dt_model.predict(X_test)

In [29]:
print("\n📌 [1] 예측값 vs 실제값 비교")
result_df = pd.DataFrame({'실제값': y_test.values, '예측값': pred_dt})
print(result_df)

print("\n📌 [2] accuracy 출력")
accuracy = accuracy_score(y_test, pred_dt)
print(f"DT 정확도: {accuracy:.4f}")

print("\n📌 [3] confusion matrix 출력") 
print(confusion_matrix(y_test, pred_dt))


📌 [1] 예측값 vs 실제값 비교
     실제값  예측값
0      0    0
1      2    2
2      2    2
3      2    2
4      2    2
..   ...  ...
427    0    0
428    2    2
429    2    2
430    0    0
431    2    2

[432 rows x 2 columns]

📌 [2] accuracy 출력
DT 정확도: 0.9676

📌 [3] confusion matrix 출력
[[ 90   0   6   0]
 [  3  14   0   1]
 [  1   0 297   0]
 [  3   0   0  17]]


In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [33]:
# 입력(X)와 타깃(y) 분리
X = df.drop(columns=["unacc"])  # 'Survived' 컬럼 제외 (입력 데이터)
y = df["unacc"]  # 'Survived' 컬럼만 저장 (타깃 데이터)

# 확인
print(X.head())  # 입력 데이터
print(y.head())  # 레이블 (타깃 변수)

   vhigh  vhigh.1  2  2.1  small  low
0      3        3  0    0      2    2
1      3        3  0    0      2    0
2      3        3  0    0      1    1
3      3        3  0    0      1    2
4      3        3  0    0      1    0
0    2
1    2
2    2
3    2
4    2
Name: unacc, dtype: int32


In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

In [37]:
# 4. 랜덤 포레스트 모델 생성 및 학습
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# 5. 예측 수행
pred_rf = rf_model.predict(X_test)

In [39]:
# 6. 결과 출력
print("\n📌 [1] 예측값 vs 실제값 비교")
result_rf = pd.DataFrame({'실제값': y_test.values, '예측값': pred_rf})
print(result_rf)

print("\n📌 [2] 정확도 출력")
accuracy = accuracy_score(y_test, pred_rf)
print(f"RF 정확도: {accuracy:.4f}")

print("\n📌 [3] confusion matrix 출력") 
print(confusion_matrix(y_test, pred_rf))


📌 [1] 예측값 vs 실제값 비교
     실제값  예측값
0      0    0
1      2    2
2      2    2
3      2    2
4      2    2
..   ...  ...
427    0    0
428    2    2
429    2    2
430    0    0
431    2    2

[432 rows x 2 columns]

📌 [2] 정확도 출력
RF 정확도: 0.9722

📌 [3] confusion matrix 출력
[[ 89   1   6   0]
 [  3  13   0   2]
 [  0   0 298   0]
 [  0   0   0  20]]


In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [43]:
# 입력(X)와 타깃(y) 분리
X = df.drop(columns=["unacc"])  # 'Survived' 컬럼 제외 (입력 데이터)
y = df["unacc"]  # 'Survived' 컬럼만 저장 (타깃 데이터)

# 확인
print(X.head())  # 입력 데이터
print(y.head())  # 레이블 (타깃 변수)

   vhigh  vhigh.1  2  2.1  small  low
0      3        3  0    0      2    2
1      3        3  0    0      2    0
2      3        3  0    0      1    1
3      3        3  0    0      1    2
4      3        3  0    0      1    0
0    2
1    2
2    2
3    2
4    2
Name: unacc, dtype: int32


In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

In [47]:
# 1. SVM 모델 생성 및 학습
svm_model = SVC(kernel="linear", random_state=42)  # 선형 커널 사용
svm_model.fit(X_train, y_train)

# 2. 예측
y_pred_svm = svm_model.predict(X_test)

In [49]:
# 6. 결과 출력
print("\n📌 [1] 예측값 vs 실제값 비교")
result_svm = pd.DataFrame({'실제값': y_test.values, '예측값': y_pred_svm})
print(result_svm)

print("\n📌 [2] 정확도 출력")
accuracy = accuracy_score(y_test, y_pred_svm)
print(f"SVM 정확도: {accuracy:.4f}")

print("\n📌 [3] confusion matrix 출력") 
print(confusion_matrix(y_test, y_pred_svm))


📌 [1] 예측값 vs 실제값 비교
     실제값  예측값
0      0    2
1      2    2
2      2    2
3      2    2
4      2    2
..   ...  ...
427    0    2
428    2    2
429    2    2
430    0    2
431    2    2

[432 rows x 2 columns]

📌 [2] 정확도 출력
SVM 정확도: 0.7083

📌 [3] confusion matrix 출력
[[ 14   0  82   0]
 [  0   0  18   0]
 [  6   0 292   0]
 [  8   0  12   0]]


In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [53]:
# 입력(X)와 타깃(y) 분리
X = df.drop(columns=["unacc"])  # 'Survived' 컬럼 제외 (입력 데이터)
y = df["unacc"]  # 'Survived' 컬럼만 저장 (타깃 데이터)

# 확인
print(X.head())  # 입력 데이터
print(y.head())  # 레이블 (타깃 변수)

   vhigh  vhigh.1  2  2.1  small  low
0      3        3  0    0      2    2
1      3        3  0    0      2    0
2      3        3  0    0      1    1
3      3        3  0    0      1    2
4      3        3  0    0      1    0
0    2
1    2
2    2
3    2
4    2
Name: unacc, dtype: int32


In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

In [57]:
# 4. 로지스틱 회귀 모델 생성 및 학습
lr_model = LogisticRegression(max_iter=200, random_state=42)
lr_model.fit(X_train, y_train)

# 5. 예측 수행
y_pred_lr = lr_model.predict(X_test)

In [59]:
# 6. 결과 출력
print("\n📌 [1] 예측값 vs 실제값 비교")
result_lr = pd.DataFrame({'실제값': y_test.values, '예측값': y_pred_lr})
print(result_lr)

print("\n📌 [2] 정확도 출력")
accuracy = accuracy_score(y_test, y_pred_lr)
print(f"LR 정확도: {accuracy:.4f}")

print("\n📌 [3] confusion matrix 출력") 
print(confusion_matrix(y_test, y_pred_lr))


📌 [1] 예측값 vs 실제값 비교
     실제값  예측값
0      0    2
1      2    2
2      2    2
3      2    2
4      2    2
..   ...  ...
427    0    2
428    2    2
429    2    0
430    0    2
431    2    2

[432 rows x 2 columns]

📌 [2] 정확도 출력
LR 정확도: 0.6944

📌 [3] confusion matrix 출력
[[ 24   0  68   4]
 [  3   0  15   0]
 [ 21   0 275   2]
 [  7   0  12   1]]


In [61]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [65]:
# 입력(X)와 타깃(y) 분리
X = df.drop(columns=["unacc"])  # 'Survived' 컬럼 제외 (입력 데이터)
y = df["unacc"]  # 'Survived' 컬럼만 저장 (타깃 데이터)

# 확인
print(X.head())  # 입력 데이터
print(y.head())  # 레이블 (타깃 변수)

   vhigh  vhigh.1  2  2.1  small  low
0      3        3  0    0      2    2
1      3        3  0    0      2    0
2      3        3  0    0      1    1
3      3        3  0    0      1    2
4      3        3  0    0      1    0
0    2
1    2
2    2
3    2
4    2
Name: unacc, dtype: int32


In [67]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

In [71]:
# 데이터 스케일링
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# KNN 모델 생성 및 학습 (k=5)
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

# 예측 및 정확도 평가
y_pred_knn = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_knn)

In [73]:
print("\n📌 [1] 예측값 vs 실제값 비교")
result_knn = pd.DataFrame({'실제값': y_test.values, '예측값': y_pred_knn})
print(result_knn)

print("\n📌 [2] 정확도 출력")
accuracy = accuracy_score(y_test, y_pred_knn)
print(f"KNN 정확도: {accuracy:.4f}")

print("\n📌 [3] confusion matrix 출력") 
print(confusion_matrix(y_test, y_pred_knn))


📌 [1] 예측값 vs 실제값 비교
     실제값  예측값
0      0    0
1      2    2
2      2    2
3      2    2
4      2    2
..   ...  ...
427    0    0
428    2    2
429    2    2
430    0    0
431    2    2

[432 rows x 2 columns]

📌 [2] 정확도 출력
KNN 정확도: 0.9352

📌 [3] confusion matrix 출력
[[ 86   1   9   0]
 [  9   8   1   0]
 [  3   0 295   0]
 [  4   0   1  15]]
